/*
 * DM_Config_Main.java
 *
 * Created on __DATE__, __TIME__
 */

package org.ost.main;

import java.awt.Component;

import javax.swing.plaf.basic.BasicTabbedPaneUI.TabbedPaneLayout;

/**
 *
 * @author  __USER__
 */
public class DM_Config_Main extends javax.swing.JPanel {

	/** Creates new form DM_Config_Main */
	public DM_Config_Main(MainClass ost) {
		this.ost = ost;
		initComponents();

		initAdditionalTabs();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		mainTabbedPane = new javax.swing.JTabbedPane();

		setBackground(new java.awt.Color(51, 51, 51));
		setLayout(new java.awt.BorderLayout());
		add(mainTabbedPane, java.awt.BorderLayout.CENTER);
	}// </editor-fold>
	//GEN-END:initComponents

	private void initAdditionalTabs() {
		tabCreatureConfig = new DM_Config_Tab_Creature(ost);

		tabConfiguration = new DM_Config_Tab_Configuration(ost);

		tabPlayers = new DM_Config_Tab_Players(ost);

		tabLogConfig = new DM_Config_Tab_Log();

		//		tabTables = new DM_Config_Tab_Tables(ost);
		//
		//		tabCharts = new DM_Config_Tab_Charts(ost);
		//
		mainTabbedPane.addTab("Bestiary", new javax.swing.ImageIcon(getClass()
				.getResource("/images/16X-Dragon-icon.png")),
				tabCreatureConfig, "Creature List");

		mainTabbedPane.addTab("Innkeeper", new javax.swing.ImageIcon(getClass()
				.getResource("/images/Inn-icon-16.png")), tabPlayers,
				"Player List");

		mainTabbedPane.addTab("Cauldron", new javax.swing.ImageIcon(getClass()
				.getResource("/images/Cauldron-icon-16.png")),
				tabConfiguration, "Configuration");
		//
		//		mainTabbedPane
		//				.addTab("Charts",
		//						new javax.swing.ImageIcon(getClass().getResource(
		//								"/images/16X-Compass-icon.png")),
		//						tabCharts,
		//						"Create tables and charts that do not require dice rolls. Usable from the DM Screen.");
		//
		//		mainTabbedPane
		//				.addTab("Tables", new javax.swing.ImageIcon(getClass()
		//						.getResource("/images/16X-d8-icon.png")), tabTables,
		//						"Create table/charts that require dice rolls. Usable from the DM Screen.");
		//
		mainTabbedPane.addTab("Log", null, tabLogConfig,
				"Log output from session");
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	public javax.swing.JTabbedPane mainTabbedPane;
	// End of variables declaration//GEN-END:variables
	public MainClass ost;
	public DM_Config_Tab_Creature tabCreatureConfig;
	public DM_Config_Tab_Log tabLogConfig;
	public DM_Config_Tab_TreasureChest tabTreasure;
	public Table_Generator tabCombat;
	public Table_Generator tabOther;
	public DM_Config_Tab_Players tabPlayers;
	public DM_Config_Tab_Configuration tabConfiguration;

} // end DM_Config_Main