/*
 * DM_Config_Tab_Configuration.java
 *
 * Created on __DATE__, __TIME__
 */

package org.ost.main;

/**
 *
 * @author  __USER__
 */
public class DM_Config_Tab_Configuration extends javax.swing.JPanel {
	MainClass ost;

	/** Creates new form DM_Config_Tab_Configuration */
	public DM_Config_Tab_Configuration(MainClass ost) {
		this.ost = ost;
		initComponents();

		initAddtionalTabs();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		configTabbedPane = new javax.swing.JTabbedPane();

		setLayout(new java.awt.BorderLayout());
		add(configTabbedPane, java.awt.BorderLayout.CENTER);
	}// </editor-fold>
	//GEN-END:initComponents

	private void initAddtionalTabs() {
//		tablesConfig = new DM_Config_Tab_Tables(ost);
//
//		chartsConfig = new DM_Config_Tab_Charts(ost);

		tabOptions = new DM_Config_Tab_Config_Options(ost);

		configTabbedPane.addTab(
				"Options",
				new javax.swing.ImageIcon(getClass().getResource(
						"/images/Saw-icon-16.png")),
				tabOptions,
				"Customize OST");

//		configTabbedPane.addTab(
//				"Charts",
//				new javax.swing.ImageIcon(getClass().getResource(
//						"/images/16X-Compass-icon.png")),
//				tabCharts,
//				"Create tables and charts that do not require dice rolls. Usable from the DM Screen.");
//
//		configTabbedPane.addTab(
//				"Tables",
//				new javax.swing.ImageIcon(getClass().getResource(
//						"/images/16X-d8-icon.png")), tabTables,
//				"Create table/charts that require dice rolls. Usable from the DM Screen.");
//
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTabbedPane configTabbedPane;
	// End of variables declaration//GEN-END:variables
	public DM_Config_Tab_Config_Options tabOptions;
}