/*
 * DM_Config_Tab_Log.java
 *
 * Created on __DATE__, __TIME__
 */

package org.ost.main;

/**
 *
 * @author  __USER__
 */
public class DM_Config_Tab_Log extends javax.swing.JPanel {

	/** Creates new form DM_Config_Tab_Log */
	public DM_Config_Tab_Log() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		ostLogTextArea = new javax.swing.JTextArea();
		jPanel1 = new javax.swing.JPanel();
		clearOSTLogButton = new javax.swing.JButton();

		setMinimumSize(new java.awt.Dimension(0, 0));
		setPreferredSize(new java.awt.Dimension(0, 0));
		setLayout(new java.awt.BorderLayout());

		ostLogTextArea.setColumns(20);
		ostLogTextArea.setRows(5);
		jScrollPane1.setViewportView(ostLogTextArea);

		add(jScrollPane1, java.awt.BorderLayout.CENTER);

		clearOSTLogButton.setText("Clear");
		clearOSTLogButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						clearOSTLogButtonActionPerformed(evt);
					}
				});
		jPanel1.add(clearOSTLogButton);

		add(jPanel1, java.awt.BorderLayout.PAGE_END);
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * 
	 */
	private void clearOSTLogButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		ostLogTextArea.setText("");
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton clearOSTLogButton;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	public static javax.swing.JTextArea ostLogTextArea;

	// End of variables declaration//GEN-END:variables

	/**
	 * log String sLog to the logtab log output
	 */
	public static void logit(String sLog) {
		ostLogTextArea.append(sLog);
	}

	/**
	 * 
	 * @param sLog
	 */
	public void debugIt(String sLog) {
		ostLogTextArea.append(sLog);
	}
}