/*
 * EncounterDungeon.java
 *
 * Created on __DATE__, __TIME__
 */

package org.ost.main;

import javax.swing.border.TitledBorder;

import org.ost.main.MyClasses.DungeonRoom;

/**
 *
 * @author  __USER__
 */
public class EncounterDungeon extends javax.swing.JPanel {
	private static final long serialVersionUID = 1L;
	private MainClass ost;

	/** Creates new form EncounterDungeon */
	public EncounterDungeon(MainClass ost, DungeonRoom dR) {
		this.ost = ost;
		this.dR = dR;
		initComponents();

		dungeonSplitPane.setDividerLocation(0.5);
		dungeonTitleBorder = (TitledBorder) this.getBorder();
		dungeonTitleBorder.setTitle(String.format("%s", dR.getName()));
		dungeonDMTextArea.setText(dR.getDescriptionGM());
		dungeonPCTextArea.setText(dR.getDescriptionPC());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		dungeonSplitPane = new javax.swing.JSplitPane();
		dungeonPCScrollPane = new javax.swing.JScrollPane();
		dungeonPCTextArea = new javax.swing.JTextArea();
		dungeonGMScrollPane = new javax.swing.JScrollPane();
		dungeonDMTextArea = new javax.swing.JTextArea();

		setBackground(new java.awt.Color(255, 255, 204));
		setBorder(javax.swing.BorderFactory.createTitledBorder(
				new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0),
						1, true), "#RoomNameHere"));
		setLayout(new java.awt.BorderLayout());

		dungeonSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
		dungeonSplitPane.setResizeWeight(0.5);

		dungeonPCScrollPane.setBackground(new java.awt.Color(204, 204, 204));
		dungeonPCScrollPane
				.setBorder(javax.swing.BorderFactory.createTitledBorder(
						new javax.swing.border.LineBorder(new java.awt.Color(0,
								0, 0), 1, true), "PC Information"));

		dungeonPCTextArea.setBackground(new java.awt.Color(204, 204, 204));
		dungeonPCTextArea.setColumns(20);
		dungeonPCTextArea.setLineWrap(true);
		dungeonPCTextArea.setRows(5);
		dungeonPCTextArea.setWrapStyleWord(true);
		dungeonPCScrollPane.setViewportView(dungeonPCTextArea);

		dungeonSplitPane.setLeftComponent(dungeonPCScrollPane);

		dungeonGMScrollPane.setBackground(new java.awt.Color(153, 153, 153));
		dungeonGMScrollPane
				.setBorder(javax.swing.BorderFactory.createTitledBorder(
						new javax.swing.border.LineBorder(new java.awt.Color(0,
								0, 0), 1, true), "GM Information"));

		dungeonDMTextArea.setBackground(new java.awt.Color(153, 153, 153));
		dungeonDMTextArea.setColumns(20);
		dungeonDMTextArea.setLineWrap(true);
		dungeonDMTextArea.setRows(5);
		dungeonDMTextArea.setWrapStyleWord(true);
		dungeonGMScrollPane.setViewportView(dungeonDMTextArea);

		dungeonSplitPane.setRightComponent(dungeonGMScrollPane);

		add(dungeonSplitPane, java.awt.BorderLayout.CENTER);
	}// </editor-fold>
	//GEN-END:initComponents

	
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	public javax.swing.JTextArea dungeonDMTextArea;
	private javax.swing.JScrollPane dungeonGMScrollPane;
	private javax.swing.JScrollPane dungeonPCScrollPane;
	public javax.swing.JTextArea dungeonPCTextArea;
	private javax.swing.JSplitPane dungeonSplitPane;
	// End of variables declaration//GEN-END:variables

	public TitledBorder dungeonTitleBorder;
	private DungeonRoom dR;
}