/*
 * Option_List_Races.java
 *
 * Created on __DATE__, __TIME__
 */

package org.ost.main;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Collections;
import java.util.List;

import javax.swing.DefaultListModel;

import org.ost.main.MyClasses.MyCellRendererList;
import org.ost.main.MyClasses.RaceClass;
import org.ost.main.MyUtils.SimpleDialog;

/**
 *
 * @author  __USER__
 */
@SuppressWarnings("serial")
public class Option_List_Races extends javax.swing.JDialog {
	MainClass ost;
	DefaultListModel<RaceClass> raceListModel;

	/** Creates new form Option_List_Races */
	public Option_List_Races(java.awt.Frame parent, boolean modal, MainClass ost) {
		super(parent, modal);
		this.ost = ost;
		initComponents();

		raceListModel = new DefaultListModel<>();
		raceListJList.setCellRenderer(new MyCellRendererList());
		raceListJList.setModel(raceListModel);
		updateRaceList();

		//		Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
		//		Dimension windowSize = parent.getSize();
		//		int windowX = Math.max(0, (screenSize.width - windowSize.width) / 2);
		//		int windowY = Math.max(0, (screenSize.height - windowSize.height) / 2);
		//		setLocation(windowX, windowY);
		//		setSize(windowSize.width - 2, windowSize.height - 2);
		//		setSize(300,500);
		setLocationRelativeTo(parent);

	}

	@SuppressWarnings("unchecked")
	private void updateRaceList() {
		// TODO Auto-generated method stub
		Object oSelected = raceListJList.getSelectedValue();
		raceListModel.removeAllElements();
		Collections.sort(ost.raceList.getContent());
		for (RaceClass oR : ost.raceList.getContent()) {
			ost.dprint("Added Race>" + oR.getName() + "\n");
			raceListModel.addElement(oR);
		}
		if (oSelected != null)
			raceListJList.setSelectedValue(oSelected, true);
		else
			raceListJList.setSelectedValue(raceListModel.getElementAt(0), true);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		mainPanel = new javax.swing.JPanel();
		jScrollPane6 = new javax.swing.JScrollPane();
		raceListJList = new javax.swing.JList();
		buttonsPanel = new javax.swing.JPanel();
		raceCreateButton = new javax.swing.JButton();
		raceEditButton = new javax.swing.JButton();
		raceDeleteButton = new javax.swing.JButton();
		raceDoneButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosed(java.awt.event.WindowEvent evt) {
				formWindowClosed(evt);
			}
		});

		mainPanel.setBackground(new java.awt.Color(153, 153, 153));
		mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(
				new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0),
						1, true), "Races",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Segoe UI", 0, 12)));
		mainPanel.setLayout(new java.awt.BorderLayout());

		raceListJList.setFont(new java.awt.Font("Segoe UI", 0, 12));
		raceListJList
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jScrollPane6.setViewportView(raceListJList);

		mainPanel.add(jScrollPane6, java.awt.BorderLayout.CENTER);

		buttonsPanel.setBackground(new java.awt.Color(204, 204, 204));
		buttonsPanel.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		raceCreateButton.setFont(new java.awt.Font("Segoe UI", 0, 12));
		raceCreateButton.setText("new");
		raceCreateButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				raceCreateButtonActionPerformed(evt);
			}
		});
		buttonsPanel.add(raceCreateButton);

		raceEditButton.setFont(new java.awt.Font("Segoe UI", 0, 12));
		raceEditButton.setText("edit");
		raceEditButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				raceEditButtonActionPerformed(evt);
			}
		});
		buttonsPanel.add(raceEditButton);

		raceDeleteButton.setBackground(new java.awt.Color(204, 0, 0));
		raceDeleteButton.setFont(new java.awt.Font("Segoe UI", 0, 12));
		raceDeleteButton.setText("delete");
		raceDeleteButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				raceDeleteButtonActionPerformed(evt);
			}
		});
		buttonsPanel.add(raceDeleteButton);

		raceDoneButton.setFont(new java.awt.Font("Segoe UI", 0, 12));
		raceDoneButton.setText("done");
		raceDoneButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				raceDoneButtonActionPerformed(evt);
			}
		});
		buttonsPanel.add(raceDoneButton);

		mainPanel.add(buttonsPanel, java.awt.BorderLayout.PAGE_END);

		getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void raceDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {
		//		Object oSelected = raceListJList.getSelectedValue();
		//		if (oSelected != null) {
		//			RaceClass oRace = (RaceClass) oSelected;
		//			if (SimpleDialog.AskYN(this, "Delete " + oRace.getName() + "?")) {
		//				ost.raceList.getContent().remove(oRace);
		//				raceListModel.removeElement(oRace);
		//			}
		//		}
		List oSelect = raceListJList.getSelectedValuesList();
		boolean bDelete = false;
		if (!oSelect.isEmpty()) {
			for (Object oSelected : oSelect)
				if (oSelected != null) {
					RaceClass o = (RaceClass) oSelected;
					String sRem = oSelect.size() > 1 ? "all selected" : o
							.getName();
					if (bDelete
							|| SimpleDialog.AskYN(this, "Remove " + sRem + "?")) {
						bDelete = true;
						ost.raceList.getContent().remove(o);
						raceListModel.removeElement(o);
					}
				}
		}
	}

	private void raceEditButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Object oSelected = raceListJList.getSelectedValue();
		if (oSelected != null && oSelected instanceof RaceClass) {
			RaceClass oRace = (RaceClass) oSelected;

			Option_AskFor_Race raceDialog = new Option_AskFor_Race(
					ost.mainFrame, true, ost, oRace);

			raceDialog.setVisible(true);

			updateRaceList();

			raceListJList.repaint();
		}
	}

	private void raceCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		RaceClass oNew = new RaceClass("NewRace",
				"Enter Description of this new race.");
		ost.raceList.add(oNew);

		Option_AskFor_Race raceDialog = new Option_AskFor_Race(ost.mainFrame,
				true, ost, oNew);

		raceDialog.setVisible(true);

		// update list with new race
		updateRaceList();
		// set selected on new race
		raceListJList.setSelectedValue(oNew, true);

		raceListJList.repaint();
	}

	private void raceDoneButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		formWindowClosed(null);
		setVisible(false);
	}

	private void formWindowClosed(java.awt.event.WindowEvent evt) {
		// TODO add your handling code here:
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JPanel buttonsPanel;
	private javax.swing.JScrollPane jScrollPane6;
	private javax.swing.JPanel mainPanel;
	private javax.swing.JButton raceCreateButton;
	private javax.swing.JButton raceDeleteButton;
	private javax.swing.JButton raceDoneButton;
	private javax.swing.JButton raceEditButton;
	private javax.swing.JList raceListJList;
	// End of variables declaration//GEN-END:variables

}