/*
 * Option_AskFor_Saves.java
 *
 * Created on __DATE__, __TIME__
 */

package org.ost.main;

import java.awt.FlowLayout;
import java.awt.Font;
import java.util.ArrayList;

import javax.swing.JPanel;
import javax.swing.JSpinner;
import static org.ost.main.MyClasses.MyStatics.*;

/**
 *
 * @author  __USER__
 */
public class Option_AskFor_Saves extends javax.swing.JDialog {
	private MainClass ost;
	private java.awt.Frame parent;
	private String[] scoreNames;
	private String[] scoreAbbrevs;
	private ArrayList<JSpinner> scores;
	private ArrayList<Integer> currentScores;


	public Option_AskFor_Saves(java.awt.Frame parent, boolean modal,
			MainClass ost, String sTitle, ArrayList<Integer> saves, boolean[] savesUsed, 
			String[] names, String[] abbrevs) {
		super(parent, modal);
		this.parent = parent;
		this.ost = ost;
		this.scoreNames = names;
		this.scoreAbbrevs = abbrevs;
		initComponents();

		setTitle(sTitle);
		mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(
				new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0),
						1, true), sTitle,
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Segoe UI", 0, 12)));

		scores = new ArrayList<JSpinner>();
		
		updatePanel(saves, savesUsed);

		setLocationRelativeTo(parent);
		//setSize(400, 300);
		pack();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		mainPanel = new javax.swing.JPanel();
		buttonsPanel = new javax.swing.JPanel();
		doneButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosed(java.awt.event.WindowEvent evt) {
				formWindowClosed(evt);
			}
		});

		mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(
				new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0),
						1, true), "TitleGoesHere",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Segoe UI", 0, 12)));
		getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

		buttonsPanel.setBackground(new java.awt.Color(204, 204, 204));
		buttonsPanel.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		doneButton.setText("done");
		doneButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				doneButtonActionPerformed(evt);
			}
		});
		buttonsPanel.add(doneButton);

		getContentPane().add(buttonsPanel, java.awt.BorderLayout.PAGE_END);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void formWindowClosed(java.awt.event.WindowEvent evt) {
		// TODO add your handling code here:
		updateValuesFromSpinners();
	}

	private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		setVisible(false);
		formWindowClosed(null);
	}

	/**
	 * put the spinner values into the abilities array
	 * 
	 * @return
	 */
	public ArrayList<Integer> updateValuesFromSpinners() {
		for (int i=0;i<scores.size();i++) {
			JSpinner sPinner = scores.get(i);
			currentScores.set(i, (int) sPinner.getValue());
		}
		return (currentScores);
	}

	/**
	 * load thief scores onto panel and activate only those marked "active"
	 * or all of active is null
	 * 
	 * second parameter is an array of boolean that can be used to make 
	 * certain thief skills not avaliable such as a monk or assassin that 
	 * does not get the full array of thief skills.
	 * 
 	 * @param scores
	 * @param active
	 */
	void updatePanel(ArrayList<Integer> iScores, boolean[] bActive) {
		//		int i = MAX_ABILITIES;
		Font fFont = new Font("Segoe UI", 0, 12);
		FlowLayout lFlow = new FlowLayout(FlowLayout.LEFT, 0, 1);

		currentScores = iScores;

		scores.clear();
		mainPanel.removeAll();
		int i = 0;
		for (Integer iE : iScores) {
			JPanel pPanel = new JPanel(lFlow);
			pPanel.setToolTipText(scoreNames[i]);
			pPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(
					new javax.swing.border.LineBorder(new java.awt.Color(0, 0,
							0), 1, true), scoreAbbrevs[i],
					javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
					javax.swing.border.TitledBorder.ABOVE_BOTTOM, fFont));
			JSpinner oJ = new JSpinner();
			oJ.setFont(fFont);
			oJ.setModel(new javax.swing.SpinnerNumberModel(0, -200, 200, 1));
			if (bActive != null)
				oJ.setEnabled(bActive[i]);
			oJ.setValue(iE);
			scores.add(oJ);
			pPanel.add(oJ);
			mainPanel.add(pPanel);
			i++;
		}

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JPanel buttonsPanel;
	private javax.swing.JButton doneButton;
	private javax.swing.JPanel mainPanel;
	// End of variables declaration//GEN-END:variables
}