/*
 * Option_AskFor_ThiefSkills.java
 *
 * Created on __DATE__, __TIME__
 */

package org.ost.main;

import java.awt.FlowLayout;
import java.awt.Font;
import java.util.ArrayList;

import javax.swing.JPanel;
import javax.swing.JSpinner;

import org.ost.main.MyClasses.SkillsClass;

import static org.ost.main.MyClasses.MyStatics.*;

/**
 *
 * @author  __USER__
 */
public class Option_AskFor_ThiefSkills extends javax.swing.JDialog {
	private MainClass ost;
	private ArrayList<JSpinner> thiefScores;
	private ArrayList<SkillsClass> currentThiefScores;

	public Option_AskFor_ThiefSkills(java.awt.Frame parent, boolean modal,
			MainClass ost, String sTitle, ArrayList<SkillsClass> thiefSkills) {
		super(parent, modal);
		this.ost = ost;
		initComponents();

		setTitle(sTitle);
		mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(
				new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0),
						1, true), sTitle,
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Segoe UI", 0, 12)));

		thiefScores = new ArrayList<JSpinner>();

		updatePanel(thiefSkills);

		setLocationRelativeTo(parent);
		setSize(440, 340);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		mainPanel = new javax.swing.JPanel();
		buttonsPanel = new javax.swing.JPanel();
		doneButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosed(java.awt.event.WindowEvent evt) {
				formWindowClosed(evt);
			}
		});

		mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(
				new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0),
						1, true), "TitleGoesHere",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Segoe UI", 0, 12)));
		getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

		buttonsPanel.setBackground(new java.awt.Color(204, 204, 204));
		buttonsPanel.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		doneButton.setText("done");
		doneButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				doneButtonActionPerformed(evt);
			}
		});
		buttonsPanel.add(doneButton);

		getContentPane().add(buttonsPanel, java.awt.BorderLayout.PAGE_END);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void formWindowClosed(java.awt.event.WindowEvent evt) {
		// TODO add your handling code here:
		updateValuesFromSpinners();
	}

	private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		setVisible(false);
		formWindowClosed(null);
	}

	/**
	 * put the spinner values into the abilities array
	 * 
	 * @return
	 */
	public ArrayList<SkillsClass> updateValuesFromSpinners() {
		for (int i = 0; i < thiefScores.size(); i++) {
			JSpinner sPinner = thiefScores.get(i);
			SkillsClass tS = currentThiefScores.get(i);
			tS.setScore((int) sPinner.getValue());
		}
		return (currentThiefScores);
	}

	/**
	 * load thief scores onto panel and activate only those marked "active"
	 * or all of active is null
	 * 
	 * second parameter is an array of boolean that can be used to make 
	 * certain thief skills not avaliable such as a monk or assassin that 
	 * does not get the full array of thief skills.
	 * 
	 * @param scores
	 * @param active
	 */
	void updatePanel(ArrayList<SkillsClass> scores) {
		//		int i = MAX_ABILITIES;
		Font fFont = new Font("Segoe UI", 0, 12);
		FlowLayout lFlow = new FlowLayout(FlowLayout.LEFT, 0, 1);

		currentThiefScores = scores;

		thiefScores.clear();
		mainPanel.removeAll();
		int i = 0;
		for (SkillsClass tS : scores) {
			JPanel pPanel = new JPanel(lFlow);
			pPanel.setToolTipText(tS.getName());
			pPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(
					new javax.swing.border.LineBorder(new java.awt.Color(0, 0,
							0), 1, true), tS.getAbbrev(),
					javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
					javax.swing.border.TitledBorder.ABOVE_BOTTOM, fFont));
			JSpinner oJ = new JSpinner();
			oJ.setFont(fFont);
			oJ.setModel(new javax.swing.SpinnerNumberModel(0, tS.getMin(), tS
					.getMax(), 1));
			oJ.setEnabled(tS.isAllowed());
			oJ.setValue(tS.getScore());
			thiefScores.add(oJ);
			pPanel.add(oJ);
			mainPanel.add(pPanel);
			i++;
		}

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JPanel buttonsPanel;
	private javax.swing.JButton doneButton;
	private javax.swing.JPanel mainPanel;
	// End of variables declaration//GEN-END:variables

}