/*
 * Panel_Player_Saves.java
 *
 * Created on __DATE__, __TIME__
 */

package org.ost.main;

import static org.ost.main.MyClasses.MyStatics.ABILITY_CHARISMA;
import static org.ost.main.MyClasses.MyStatics.ABILITY_COMELINESS;
import static org.ost.main.MyClasses.MyStatics.ABILITY_CONSTITUTION;
import static org.ost.main.MyClasses.MyStatics.ABILITY_DEXTERITY;
import static org.ost.main.MyClasses.MyStatics.ABILITY_INTELLIGENCE;
import static org.ost.main.MyClasses.MyStatics.ABILITY_STRENGTH;
import static org.ost.main.MyClasses.MyStatics.ABILITY_WISDOM;
import static org.ost.main.MyClasses.MyStatics.AC_NAMES;
import static org.ost.main.MyClasses.MyStatics.AC_NORMAL;
import static org.ost.main.MyClasses.MyStatics.AC_REAR;
import static org.ost.main.MyClasses.MyStatics.AC_SHIELDLESS;
import static org.ost.main.MyClasses.MyStatics.ALIGNMENTS;
import static org.ost.main.MyClasses.MyStatics.DEFAULT_FONT;
import static org.ost.main.MyClasses.MyStatics.MAX_CLERIC_SPELL_LEVEL;
import static org.ost.main.MyClasses.MyStatics.MAX_MAGE_SPELL_LEVEL;
import static org.ost.main.MyClasses.MyStatics.SAVES;
import static org.ost.main.MyClasses.MyStatics.SAVE_BREATH;
import static org.ost.main.MyClasses.MyStatics.SAVE_DEATH;
import static org.ost.main.MyClasses.MyStatics.SAVE_POLY;
import static org.ost.main.MyClasses.MyStatics.SAVE_ROD;
import static org.ost.main.MyClasses.MyStatics.SAVE_SPELL;
import static org.ost.main.MyClasses.MyStatics.STRENGTH_PERCENT_100;
import static org.ost.main.MyClasses.MyStatics.STRENGTH_PERCENT_1_50;
import static org.ost.main.MyClasses.MyStatics.STRENGTH_PERCENT_51_75;
import static org.ost.main.MyClasses.MyStatics.STRENGTH_PERCENT_76_90;
import static org.ost.main.MyClasses.MyStatics.STRENGTH_PERCENT_91_99;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.ArrayList;

import javax.swing.JLabel;
import javax.swing.JPanel;

import org.ost.main.MyClasses.AbilityScoreClass;
import org.ost.main.MyClasses.AbilityStatClass;
import org.ost.main.MyClasses.PlayerClass;
import org.ost.main.MyClasses.RaceClass;
import org.ost.main.MyClasses.SkillsClass;

/**
 *
 * @author  __USER__
 */
public class Panel_Player_Saves extends javax.swing.JPanel {
	private MainClass ost;
	private PlayerClass pc;

	/** Creates new form Panel_Player_Saves */
	public Panel_Player_Saves(MainClass ost, PlayerClass oPlayer) {
		this.ost = ost;
		this.pc = oPlayer;
		initComponents();
		updatePanel(oPlayer);
	}

	public void updatePanel(PlayerClass oPlayer) {
		// TODO Auto-generated method stub
		// added this incase we updated panel
		pc = oPlayer;

		RaceClass race = oPlayer.getMyRace().getRaceByID(ost.raceList);

		// saves
		ArrayList<Integer> bestSaves = pc.getAllSaves(ost.characterClassList,
				ost.extraAbilitiesList, ost.raceList);
		pc.setMySaves(bestSaves);

		ArrayList<Integer> bestSaveAdj = pc.getAllSaveAdjustments(
				ost.characterClassList, ost.extraAbilitiesList, ost.raceList,
				ost.abilityStatList);
		pc.setMySaveAdjustments(bestSaveAdj);

		for (int i = 0; i < pc.getMySaves().size(); i++) {
			int aB = pc.getMySaves().get(i);
			int aJ = pc.getMySaveAdjustments().get(i);
			switch (i) {
			case SAVE_BREATH:
				pcSaveBreathLabel.setText(String.format("%d", (aB - aJ)));
				pcSaveBreathLabel
						.setToolTipText(SAVES[i] + ":" + aB + "+" + aJ);
				spellsSaveLabel.setText(SAVES[i]);
				break;
			case SAVE_DEATH:
				pcSavePoisonLabel.setText(String.format("%d", (aB - aJ)));
				pcSavePoisonLabel
						.setToolTipText(SAVES[i] + ":" + aB + "+" + aJ);
				deathSaveLabel.setText(SAVES[i]);
				break;
			case SAVE_POLY:
				pcSavePolyLabel.setText(String.format("%d", (aB - aJ)));
				pcSavePolyLabel.setToolTipText(SAVES[i] + ":" + aB + "+" + aJ);
				polySaveLabel.setText(SAVES[i]);
				break;
			case SAVE_ROD:
				pcSaveRodLabel.setText(String.format("%d", (aB - aJ)));
				pcSaveRodLabel.setToolTipText(SAVES[i] + ":" + aB + "+" + aJ);
				rodSaveLabel.setText(SAVES[i]);
				break;
			case SAVE_SPELL:
				pcSaveSpellsLabel.setText(String.format("%d", (aB - aJ)));
				pcSaveSpellsLabel
						.setToolTipText(SAVES[i] + ":" + aB + "+" + aJ);
				spellsSaveLabel.setText(SAVES[i]);
				break;

			default:
				ost.dprint("Unknown save type in Panel_Player updatePanel()\n");
				break;
			}

		}

		repaint();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		savesPanel = new javax.swing.JPanel();
		pcSavePoisonLabel = new javax.swing.JLabel();
		deathSaveLabel = new javax.swing.JLabel();
		pcSavePolyLabel = new javax.swing.JLabel();
		pcSaveRodLabel = new javax.swing.JLabel();
		pcSaveBreathLabel = new javax.swing.JLabel();
		pcSaveSpellsLabel = new javax.swing.JLabel();
		polySaveLabel = new javax.swing.JLabel();
		rodSaveLabel = new javax.swing.JLabel();
		breathSaveLabel = new javax.swing.JLabel();
		spellsSaveLabel = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();

		setLayout(new java.awt.BorderLayout());

		savesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(
				new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0),
						1, true), "Saves"));
		savesPanel.setLayout(new java.awt.GridBagLayout());

		pcSavePoisonLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcSavePoisonLabel.setText("00");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
		savesPanel.add(pcSavePoisonLabel, gridBagConstraints);

		deathSaveLabel.setFont(new java.awt.Font("Segoe UI", 2, 12));
		deathSaveLabel.setText("Poison/Paralyzation");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		savesPanel.add(deathSaveLabel, gridBagConstraints);

		pcSavePolyLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcSavePolyLabel.setText("00");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
		savesPanel.add(pcSavePolyLabel, gridBagConstraints);

		pcSaveRodLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcSaveRodLabel.setText("00");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
		savesPanel.add(pcSaveRodLabel, gridBagConstraints);

		pcSaveBreathLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcSaveBreathLabel.setText("00");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
		savesPanel.add(pcSaveBreathLabel, gridBagConstraints);

		pcSaveSpellsLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcSaveSpellsLabel.setText("00");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
		savesPanel.add(pcSaveSpellsLabel, gridBagConstraints);

		polySaveLabel.setFont(new java.awt.Font("Segoe UI", 2, 12));
		polySaveLabel.setText("Petrify/Poly");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		savesPanel.add(polySaveLabel, gridBagConstraints);

		rodSaveLabel.setFont(new java.awt.Font("Segoe UI", 2, 12));
		rodSaveLabel.setText("Rod/Staff/Wand");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		savesPanel.add(rodSaveLabel, gridBagConstraints);

		breathSaveLabel.setFont(new java.awt.Font("Segoe UI", 2, 12));
		breathSaveLabel.setText("Breath");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		savesPanel.add(breathSaveLabel, gridBagConstraints);

		spellsSaveLabel.setFont(new java.awt.Font("Segoe UI", 2, 12));
		spellsSaveLabel.setText("Spells");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		savesPanel.add(spellsSaveLabel, gridBagConstraints);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0,
				Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0,
				Short.MAX_VALUE));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 5;
		gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
		gridBagConstraints.weightx = 5.0;
		gridBagConstraints.weighty = 5.0;
		savesPanel.add(jPanel1, gridBagConstraints);

		add(savesPanel, java.awt.BorderLayout.CENTER);
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel breathSaveLabel;
	private javax.swing.JLabel deathSaveLabel;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JLabel pcSaveBreathLabel;
	private javax.swing.JLabel pcSavePoisonLabel;
	private javax.swing.JLabel pcSavePolyLabel;
	private javax.swing.JLabel pcSaveRodLabel;
	private javax.swing.JLabel pcSaveSpellsLabel;
	private javax.swing.JLabel polySaveLabel;
	private javax.swing.JLabel rodSaveLabel;
	private javax.swing.JPanel savesPanel;
	private javax.swing.JLabel spellsSaveLabel;
	// End of variables declaration//GEN-END:variables

}