/*
 * Panel_Player_DivineSpells.java
 *
 * Created on __DATE__, __TIME__
 */

package org.ost.main;

import static org.ost.main.MyClasses.MyStatics.DEFAULT_FONT;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;

import javax.swing.JLabel;
import javax.swing.JPanel;

import org.ost.main.MyClasses.PlayerClass;

/**
 *
 * @author  __USER__
 */
public class Panel_Player_DivineSpells extends javax.swing.JPanel {
	private MainClass ost;
	private PlayerClass pc;

	/** Creates new form Panel_Player_DivineSpells */
	public Panel_Player_DivineSpells(MainClass ost, PlayerClass oPlayer) {
		this.ost = ost;
		this.pc = oPlayer;
		initComponents();
		updatePanel(oPlayer);
	}

	public void updatePanel(PlayerClass oPlayer) {
		// TODO Auto-generated method stub
		// added this incase we updated panel
		pc = oPlayer;

		// divine spells
		int divineBase[] = pc.getAllDivineSpellsPerLevel(ost);
		int divineAdj[] = pc.getAllDivineBonusSpellsPerLevel(ost);

		divineSpellsPanel.removeAll();

		Font fFont = new Font(DEFAULT_FONT, Font.PLAIN, 10);

		Color aColor = new Color(255, 204, 105);
		Color bColor = new Color(255, 153, 51);

		boolean bFlip = false;

		JLabel sLevel = new JLabel(String.format("Level"));
		JPanel pLevel = new JPanel(new FlowLayout(FlowLayout.LEFT));
		pLevel.setBackground(new Color(204, 204, 204));
		sLevel.setToolTipText("Spell Level");
		sLevel.setFont(fFont);
		pLevel.add(sLevel);
		divineSpellsPanel.add(pLevel);

		for (int i = 0; i < divineBase.length; i++) {
			int base = divineBase[i];
			if (base != 0) {
				JLabel n = new JLabel(String.format("Level %d", (i + 1)));
				n.setFont(fFont);
				JPanel p = new JPanel(new FlowLayout(FlowLayout.LEFT));
				p.setBackground(bFlip ? bColor : aColor);
				bFlip = !bFlip;
				n.setToolTipText("Spell Level " + (i + 1));
				p.setToolTipText(n.getToolTipText());
				p.add(n);
				divineSpellsPanel.add(p);
			}
		}

		bFlip = false;
		JLabel sSpells = new JLabel(String.format("Count"));
		JPanel pSpells = new JPanel(new FlowLayout(FlowLayout.LEFT));
		pSpells.setBackground(new Color(204, 204, 204));
		sSpells.setToolTipText("Number of Spells Slots");
		sSpells.setFont(fFont);
		pSpells.add(sSpells);
		divineSpellsPanel.add(pSpells);

		for (int i = 0; i < divineBase.length; i++) {
			int base = divineBase[i];
			int adj = divineAdj[i];
			int finalSkill = base + adj;
			if (base != 0) {
				JLabel n = new JLabel(String.format("%d", finalSkill));
				n.setFont(fFont);
				JPanel p = new JPanel(new FlowLayout(FlowLayout.LEFT));
				p.setBackground(bFlip ? bColor : aColor);
				bFlip = !bFlip;
				n.setToolTipText("Level " + (i + 1) + ": " + base + "+" + adj);
				p.setToolTipText(n.getToolTipText());
				p.add(n);
				divineSpellsPanel.add(p);
			}
		}

		//		for (int i = 0; i < divineBase.length; i++) {
		//			JPanel divinePanel = new JPanel(new GridLayout(2, 0, 1, 1));
		//			divinePanel.setBorder(new javax.swing.border.LineBorder(
		//					new java.awt.Color(0, 0, 0), 1, true));
		//			int base = divineBase[i];
		//			int adj = divineAdj[i];
		//			int finalSkill = base + adj;
		//			if (base != 0) {
		//				String tooltip = "Level " + (i + 1) + ": " + base + "+" + adj;
		//				divinePanel.setToolTipText(tooltip);
		//				JLabel name = new JLabel("L" + (i + 1));
		//				name.setToolTipText(tooltip);
		//				JLabel value = new JLabel(String.format("%d", finalSkill));
		//				value.setToolTipText(tooltip);
		//
		//				divinePanel.add(name);
		//				divinePanel.add(value);
		//				divineSpellsPanel.add(divinePanel);
		//			}
		//		}
		//		divineSpellsPanel.revalidate();

		repaint();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		divineSpellsPanel = new javax.swing.JPanel();

		setBackground(new java.awt.Color(255, 255, 255));
		setLayout(new java.awt.BorderLayout());

		divineSpellsPanel.setBackground(new java.awt.Color(255, 255, 255));
		divineSpellsPanel.setBorder(javax.swing.BorderFactory
				.createTitledBorder(new javax.swing.border.LineBorder(
						new java.awt.Color(0, 0, 0), 1, true), "Divine"));
		divineSpellsPanel.setLayout(new java.awt.GridLayout(2, 0, 1, 1));
		add(divineSpellsPanel, java.awt.BorderLayout.WEST);
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JPanel divineSpellsPanel;
	// End of variables declaration//GEN-END:variables

}