/*
 * Panel_Player_Saves.java
 *
 * Created on __DATE__, __TIME__
 */

package org.ost.main;

import static org.ost.main.MyClasses.MyStatics.ABILITY_CHARISMA;
import static org.ost.main.MyClasses.MyStatics.ABILITY_COMELINESS;
import static org.ost.main.MyClasses.MyStatics.ABILITY_CONSTITUTION;
import static org.ost.main.MyClasses.MyStatics.ABILITY_DEXTERITY;
import static org.ost.main.MyClasses.MyStatics.ABILITY_INTELLIGENCE;
import static org.ost.main.MyClasses.MyStatics.ABILITY_STRENGTH;
import static org.ost.main.MyClasses.MyStatics.ABILITY_WISDOM;
import static org.ost.main.MyClasses.MyStatics.AC_NAMES;
import static org.ost.main.MyClasses.MyStatics.AC_NORMAL;
import static org.ost.main.MyClasses.MyStatics.AC_REAR;
import static org.ost.main.MyClasses.MyStatics.AC_SHIELDLESS;
import static org.ost.main.MyClasses.MyStatics.ALIGNMENTS;
import static org.ost.main.MyClasses.MyStatics.DEFAULT_FONT;
import static org.ost.main.MyClasses.MyStatics.MAX_CLERIC_SPELL_LEVEL;
import static org.ost.main.MyClasses.MyStatics.MAX_MAGE_SPELL_LEVEL;
import static org.ost.main.MyClasses.MyStatics.SAVES;
import static org.ost.main.MyClasses.MyStatics.SAVE_BREATH;
import static org.ost.main.MyClasses.MyStatics.SAVE_DEATH;
import static org.ost.main.MyClasses.MyStatics.SAVE_POLY;
import static org.ost.main.MyClasses.MyStatics.SAVE_ROD;
import static org.ost.main.MyClasses.MyStatics.SAVE_SPELL;
import static org.ost.main.MyClasses.MyStatics.STRENGTH_PERCENT_100;
import static org.ost.main.MyClasses.MyStatics.STRENGTH_PERCENT_1_50;
import static org.ost.main.MyClasses.MyStatics.STRENGTH_PERCENT_51_75;
import static org.ost.main.MyClasses.MyStatics.STRENGTH_PERCENT_76_90;
import static org.ost.main.MyClasses.MyStatics.STRENGTH_PERCENT_91_99;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.ArrayList;

import javax.swing.JLabel;
import javax.swing.JPanel;

import org.ost.main.MyClasses.AbilityScoreClass;
import org.ost.main.MyClasses.AbilityStatClass;
import org.ost.main.MyClasses.PlayerClass;
import org.ost.main.MyClasses.RaceClass;
import org.ost.main.MyClasses.SkillsClass;

/**
 *
 * @author  __USER__
 */
public class Panel_Player_Saves extends javax.swing.JPanel {
	private MainClass ost;
	private PlayerClass pc;

	/** Creates new form Panel_Player_Saves */
	public Panel_Player_Saves(MainClass ost, PlayerClass oPlayer) {
		this.ost = ost;
		this.pc = oPlayer;
		initComponents();
		updatePanel(oPlayer);
	}

	public void updatePanel(PlayerClass oPlayer) {
		// TODO Auto-generated method stub
		// added this incase we updated panel
		pc = oPlayer;

		RaceClass race = oPlayer.getMyRace().getRaceByID(ost.raceList);

		// saves
		ArrayList<Integer> bestSaves = pc.getAllSaves(ost.characterClassList,
				ost.extraAbilitiesList, ost.raceList);
		pc.setMySaves(bestSaves);

		ArrayList<Integer> bestSaveAdj = pc.getAllSaveAdjustments(
				ost.characterClassList, ost.extraAbilitiesList, ost.raceList);
		pc.setMySaveAdjustments(bestSaveAdj);

		for (int i = 0; i < pc.getMySaves().size(); i++) {
			int aB = pc.getMySaves().get(i);
			int aJ = pc.getMySaveAdjustments().get(i);
			switch (i) {
			case SAVE_BREATH:
				pcSaveBreathLabel.setText(String.format("%d", (aB - aJ)));
				pcSaveBreathLabel
						.setToolTipText(SAVES[i] + ":" + aB + "+" + aJ);
				break;
			case SAVE_DEATH:
				pcSavePoisonLabel.setText(String.format("%d", (aB - aJ)));
				pcSavePoisonLabel
						.setToolTipText(SAVES[i] + ":" + aB + "+" + aJ);
				break;
			case SAVE_POLY:
				pcSavePolyLabel.setText(String.format("%d", (aB - aJ)));
				pcSavePolyLabel.setToolTipText(SAVES[i] + ":" + aB + "+" + aJ);
				break;
			case SAVE_ROD:
				pcSaveRodLabel.setText(String.format("%d", (aB - aJ)));
				pcSaveRodLabel.setToolTipText(SAVES[i] + ":" + aB + "+" + aJ);
				break;
			case SAVE_SPELL:
				pcSaveSpellsLabel.setText(String.format("%d", (aB - aJ)));
				pcSaveSpellsLabel
						.setToolTipText(SAVES[i] + ":" + aB + "+" + aJ);
				break;

			default:
				ost.dprint("Unknown save type in Panel_Player updatePanel()\n");
				break;
			}

		}


		repaint();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		savesPanel = new javax.swing.JPanel();
		pcSavePoisonLabel = new javax.swing.JLabel();
		jLabel27 = new javax.swing.JLabel();
		pcSavePolyLabel = new javax.swing.JLabel();
		pcSaveRodLabel = new javax.swing.JLabel();
		pcSaveBreathLabel = new javax.swing.JLabel();
		pcSaveSpellsLabel = new javax.swing.JLabel();
		jLabel37 = new javax.swing.JLabel();
		jLabel39 = new javax.swing.JLabel();
		jLabel41 = new javax.swing.JLabel();
		jLabel43 = new javax.swing.JLabel();

		setLayout(new java.awt.BorderLayout());

		savesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(
				new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0),
						1, true), "Saves"));

		pcSavePoisonLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcSavePoisonLabel.setText("00");

		jLabel27.setFont(new java.awt.Font("Segoe UI", 2, 12));
		jLabel27.setText("Poison/Paralyzation");

		pcSavePolyLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcSavePolyLabel.setText("00");

		pcSaveRodLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcSaveRodLabel.setText("00");

		pcSaveBreathLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcSaveBreathLabel.setText("00");

		pcSaveSpellsLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcSaveSpellsLabel.setText("00");

		jLabel37.setFont(new java.awt.Font("Segoe UI", 2, 12));
		jLabel37.setText("Petrify/Poly");

		jLabel39.setFont(new java.awt.Font("Segoe UI", 2, 12));
		jLabel39.setText("Rod/Staff/Wand");

		jLabel41.setFont(new java.awt.Font("Segoe UI", 2, 12));
		jLabel41.setText("Breath");

		jLabel43.setFont(new java.awt.Font("Segoe UI", 2, 12));
		jLabel43.setText("Spells");

		javax.swing.GroupLayout savesPanelLayout = new javax.swing.GroupLayout(
				savesPanel);
		savesPanel.setLayout(savesPanelLayout);
		savesPanelLayout
				.setHorizontalGroup(savesPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								savesPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												savesPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																savesPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				pcSavePoisonLabel)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel27))
														.addGroup(
																savesPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				pcSavePolyLabel)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel37))
														.addGroup(
																savesPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				pcSaveRodLabel)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel39))
														.addGroup(
																savesPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				pcSaveBreathLabel)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel41))
														.addGroup(
																savesPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				pcSaveSpellsLabel)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel43)))
										.addContainerGap(18, Short.MAX_VALUE)));
		savesPanelLayout
				.setVerticalGroup(savesPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								savesPanelLayout
										.createSequentialGroup()
										.addGroup(
												savesPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																pcSavePoisonLabel)
														.addComponent(jLabel27))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												savesPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																pcSavePolyLabel)
														.addComponent(jLabel37))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												savesPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																pcSaveRodLabel)
														.addComponent(jLabel39))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												savesPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																pcSaveBreathLabel)
														.addComponent(jLabel41))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												savesPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																pcSaveSpellsLabel)
														.addComponent(jLabel43))
										.addContainerGap(26, Short.MAX_VALUE)));

		add(savesPanel, java.awt.BorderLayout.CENTER);
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel27;
	private javax.swing.JLabel jLabel37;
	private javax.swing.JLabel jLabel39;
	private javax.swing.JLabel jLabel41;
	private javax.swing.JLabel jLabel43;
	private javax.swing.JLabel pcSaveBreathLabel;
	private javax.swing.JLabel pcSavePoisonLabel;
	private javax.swing.JLabel pcSavePolyLabel;
	private javax.swing.JLabel pcSaveRodLabel;
	private javax.swing.JLabel pcSaveSpellsLabel;
	private javax.swing.JPanel savesPanel;
	// End of variables declaration//GEN-END:variables

}