/*
 * Panel_Player_DivineSpells.java
 *
 * Created on __DATE__, __TIME__
 */

package org.ost.main;

import java.awt.GridLayout;

import javax.swing.JLabel;
import javax.swing.JPanel;

import org.ost.main.MyClasses.PlayerClass;

/**
 *
 * @author  __USER__
 */
public class Panel_Player_DivineSpells extends javax.swing.JPanel {
	private MainClass ost;
	private PlayerClass pc;

	/** Creates new form Panel_Player_DivineSpells */
	public Panel_Player_DivineSpells(MainClass ost, PlayerClass oPlayer) {
		this.ost = ost;
		this.pc = oPlayer;
		initComponents();
		updatePanel(oPlayer);
	}

	public void updatePanel(PlayerClass oPlayer) {
		// TODO Auto-generated method stub
		// added this incase we updated panel
		pc = oPlayer;

		// divine spells
		int divineBase[] = pc.getAllDivineSpellsPerLevel(
				ost.characterClassList, ost.extraAbilitiesList, ost.raceList);
		int divineAdj[] = pc.getAllDivineBonusSpellsPerLevel(
				ost.characterClassList, ost.extraAbilitiesList, ost.raceList,
				ost.abilityStatList);

		divineSpellsPanel.removeAll();
		for (int i = 0; i < divineBase.length; i++) {
			JPanel divinePanel = new JPanel(new GridLayout(2, 0, 1, 1));
			int base = divineBase[i];
			int adj = divineAdj[i];
			int finalSkill = base + adj;
			if (base != 0) {
				String tooltip = "Level " + (i + 1) + ": " + base + "+" + adj;
				JLabel name = new JLabel("L" + (i + 1));
				name.setToolTipText(tooltip);
				JLabel value = new JLabel(String.format("%d", finalSkill));
				value.setToolTipText(tooltip);

				divinePanel.add(name);
				divinePanel.add(value);
				divineSpellsPanel.add(divinePanel);
			}
		}
		divineSpellsPanel.revalidate();

		repaint();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		divineSpellsPanel = new javax.swing.JPanel();

		setLayout(new java.awt.BorderLayout());

		divineSpellsPanel
				.setBorder(javax.swing.BorderFactory.createTitledBorder(
						new javax.swing.border.LineBorder(new java.awt.Color(0,
								0, 0), 1, true), "Divine Spells"));
		divineSpellsPanel.setLayout(new java.awt.FlowLayout(
				java.awt.FlowLayout.LEFT));
		add(divineSpellsPanel, java.awt.BorderLayout.CENTER);
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JPanel divineSpellsPanel;
	// End of variables declaration//GEN-END:variables

}