/*
 * Panel_Player_Details.java
 *
 * Created on __DATE__, __TIME__
 */

package org.ost.main;

import static org.ost.main.MyClasses.MyStatics.*;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.ArrayList;

import javax.swing.JLabel;
import javax.swing.JPanel;

import org.ost.main.MyClasses.AbilityScoreClass;
import org.ost.main.MyClasses.AbilityStatClass;
import org.ost.main.MyClasses.PlayerClass;
import org.ost.main.MyClasses.RaceClass;
import org.ost.main.MyClasses.SkillsClass;

/**
 *
 * @author  __USER__
 */
public class Panel_Player_Details extends javax.swing.JPanel {
	private MainClass ost;
	private PlayerClass pc;

	/** Creates new form Panel_Player_Details */
	public Panel_Player_Details(MainClass ost, PlayerClass oPlayer) {
		this.ost = ost;
		this.pc = oPlayer;
		initComponents();
		
		updatePanel(oPlayer);
	}

	public void updatePanel(PlayerClass oPlayer) {
		// TODO Auto-generated method stub
		// added this incase we updated panel
		pc = oPlayer;

		RaceClass race = oPlayer.getMyRace().getRaceByID(ost.raceList);
		// portrait

		// details
		pcCharacterNameLabel.setText(pc.getName());
		pcPlayerNameLabel.setText(pc.getNamePlayer());
		pcAlignmentLabel.setText(ALIGNMENTS[pc.getMyAlignmentType()]);
		pcRaceLabel.setText(pc.getMyRaceName(ost.raceList));
		pcClassNameLabel.setText(pc.getMyClassName(ost.characterClassList));
		pcClassLevelLabel.setText(pc.getMyLevelName(ost.characterClassList));
		pcExperienceTotalsLabel.setText(pc
				.getMyExperienceName(ost.characterClassList));
		pcMoveBaseLabel.setText(pc.getMoveRate());
		if (race != null)
			pcMoveBaseLabel.setText(String.format("%d", race.getMoveRate()));

		repaint();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		detailsPanel = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		pcCharacterNameLabel = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		pcClassNameLabel = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		pcRaceLabel = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		pcAlignmentLabel = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		pcClassLevelLabel = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		pcPlayerNameLabel = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		pcMoveBaseLabel = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		pcExperienceTotalsLabel = new javax.swing.JLabel();

		setLayout(new java.awt.BorderLayout());

		detailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(
				new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0),
						1, true), "Details"));

		jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12));
		jLabel3.setText("Name");

		pcCharacterNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcCharacterNameLabel.setText("pcCharacterName");

		jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12));
		jLabel5.setText("Class");

		pcClassNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcClassNameLabel.setText("pcClass");

		jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12));
		jLabel9.setText("Race");

		pcRaceLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcRaceLabel.setText("pcRace");

		jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12));
		jLabel11.setText("Alignment");

		pcAlignmentLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcAlignmentLabel.setText("pcAlignment");

		jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12));
		jLabel7.setText("Level");

		pcClassLevelLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcClassLevelLabel.setText("pcClassLevel");

		jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12));
		jLabel1.setText("Player Name");

		pcPlayerNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcPlayerNameLabel.setText("pcPlayerName");

		jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 12));
		jLabel13.setText("Move-base");

		pcMoveBaseLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcMoveBaseLabel.setText("pcMoveBase");

		jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12));
		jLabel6.setText("EXP");
		jLabel6.setToolTipText("Total Experience");

		pcExperienceTotalsLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcExperienceTotalsLabel.setText("pcExperience");

		javax.swing.GroupLayout detailsPanelLayout = new javax.swing.GroupLayout(
				detailsPanel);
		detailsPanel.setLayout(detailsPanelLayout);
		detailsPanelLayout
				.setHorizontalGroup(detailsPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								detailsPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												detailsPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																detailsPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel3)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				pcCharacterNameLabel))
														.addGroup(
																detailsPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel5)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				pcClassNameLabel))
														.addGroup(
																detailsPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel11)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				pcAlignmentLabel))
														.addGroup(
																detailsPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel6)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				pcExperienceTotalsLabel)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												detailsPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																detailsPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel13)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				pcMoveBaseLabel))
														.addGroup(
																detailsPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel9)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				pcRaceLabel))
														.addGroup(
																detailsPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel7)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				pcClassLevelLabel))
														.addGroup(
																detailsPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel1)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				pcPlayerNameLabel)))
										.addContainerGap(27, Short.MAX_VALUE)));
		detailsPanelLayout
				.setVerticalGroup(detailsPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								detailsPanelLayout
										.createSequentialGroup()
										.addGroup(
												detailsPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																pcCharacterNameLabel,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jLabel3,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																pcPlayerNameLabel,
																javax.swing.GroupLayout.Alignment.TRAILING))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												detailsPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel5,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																pcClassNameLabel,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jLabel7,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																pcClassLevelLabel,
																javax.swing.GroupLayout.Alignment.TRAILING))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												detailsPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel6,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																pcExperienceTotalsLabel,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																pcRaceLabel,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jLabel9,
																javax.swing.GroupLayout.Alignment.TRAILING))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												detailsPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel11,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																pcAlignmentLabel,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jLabel13,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																pcMoveBaseLabel,
																javax.swing.GroupLayout.Alignment.TRAILING))
										.addContainerGap(26, Short.MAX_VALUE)));

		add(detailsPanel, java.awt.BorderLayout.CENTER);
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JPanel detailsPanel;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JLabel pcAlignmentLabel;
	private javax.swing.JLabel pcCharacterNameLabel;
	private javax.swing.JLabel pcClassLevelLabel;
	private javax.swing.JLabel pcClassNameLabel;
	private javax.swing.JLabel pcExperienceTotalsLabel;
	private javax.swing.JLabel pcMoveBaseLabel;
	private javax.swing.JLabel pcPlayerNameLabel;
	private javax.swing.JLabel pcRaceLabel;
	// End of variables declaration//GEN-END:variables

}