/*
 * Panel_Player_Details.java
 *
 * Created on __DATE__, __TIME__
 */

package org.ost.main;

import static org.ost.main.MyClasses.MyStatics.*;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.ArrayList;

import javax.swing.JLabel;
import javax.swing.JPanel;

import org.ost.main.MyClasses.AbilityScoreClass;
import org.ost.main.MyClasses.AbilityStatClass;
import org.ost.main.MyClasses.PlayerClass;
import org.ost.main.MyClasses.RaceClass;
import org.ost.main.MyClasses.SkillsClass;

/**
 *
 * @author  __USER__
 */
public class Panel_Player_Details extends javax.swing.JPanel {
	private MainClass ost;
	private PlayerClass pc;

	/** Creates new form Panel_Player_Details */
	public Panel_Player_Details(MainClass ost, PlayerClass oPlayer) {
		this.ost = ost;
		this.pc = oPlayer;
		initComponents();

		updatePanel(oPlayer);
	}

	public void updatePanel(PlayerClass oPlayer) {
		// TODO Auto-generated method stub
		// added this incase we updated panel
		pc = oPlayer;

		// details
		pcCharacterNameLabel.setText(pc.getName());
		pcPlayerNameLabel.setText(pc.getNamePlayer());
		pcAlignmentLabel.setText(ALIGNMENTS[pc.getMyAlignmentType()]);
		pcRaceLabel.setText(pc.getMyRaceName(ost.raceList));
		pcClassNameLabel.setText(pc.getMyClassName(ost));
		pcClassLevelLabel.setText(pc.getMyLevelName(ost));
		pcExperienceTotalsLabel.setText(pc
				.getMyExperienceName(ost.characterClassList));
		pcMoveBaseLabel.setText(pc.getMoveRate());
		pcMoveBaseLabel
				.setText(String.format("%d", pc.getModifiedMoveRate(ost)));

		//		pcCurrentHPLabel.setText(String.format("%d", pc.getHpCurrent()));
		pcMaxHPLabel.setText(String.format("%d", pc.getHpMax()));
		int iTHACO = pc.getTHACO(ost);
		pcTHACOLabel.setText(String.format("%d", iTHACO));
		pcTHACOLabel.setToolTipText("Roll needed to hit armor class 0 is "
				+ iTHACO);

		for (int i = 0; i < pc.getArmorRatings().size(); i++) {
			switch (i) {
			case AC_NORMAL: {
				int setAC = pc.getArmorClassByType(AC_NORMAL, ost);
				pcArmorClassLabel.setText(String.format("%d", setAC));
				pcArmorClassLabel.setToolTipText(AC_NAMES[i] + "," + ost.log);
			}
				break;
			case AC_REAR: {
				int setACRear = pc.getArmorClassByType(AC_REAR, ost);
				pcArmorClassRearLabel.setText(String.format("%d", setACRear));
				pcArmorClassRearLabel.setToolTipText(AC_NAMES[i] + ","
						+ ost.log);
			}
				break;
			case AC_SHIELDLESS: {
				int setACShieldless = pc
						.getArmorClassByType(AC_SHIELDLESS, ost);
				pcArmorClassShieldlessLabel.setText(String.format("%d",
						setACShieldless));
			}
				pcArmorClassShieldlessLabel.setToolTipText(AC_NAMES[i] + ","
						+ ost.log);
				break;

			default:
				ost.dprint("Unknown AC type in Panel_Player_Combat updatePanel()\n");
				break;
			}
		}

		repaint();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		detailsPanel = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		pcCharacterNameLabel = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		pcClassNameLabel = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		pcRaceLabel = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		pcAlignmentLabel = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		pcClassLevelLabel = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		pcPlayerNameLabel = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		pcMoveBaseLabel = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		pcExperienceTotalsLabel = new javax.swing.JLabel();
		jLabel45 = new javax.swing.JLabel();
		pcMaxHPLabel = new javax.swing.JLabel();
		jLabel29 = new javax.swing.JLabel();
		pcArmorClassLabel = new javax.swing.JLabel();
		jLabel31 = new javax.swing.JLabel();
		pcArmorClassShieldlessLabel = new javax.swing.JLabel();
		jLabel33 = new javax.swing.JLabel();
		pcArmorClassRearLabel = new javax.swing.JLabel();
		jLabel47 = new javax.swing.JLabel();
		pcTHACOLabel = new javax.swing.JLabel();

		setLayout(new java.awt.BorderLayout());

		detailsPanel.setBackground(new java.awt.Color(255, 255, 255));
		detailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(
				new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0),
						1, true), "Details"));

		jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12));
		jLabel3.setText("Name");

		pcCharacterNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcCharacterNameLabel.setText("name");

		jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12));
		jLabel5.setText("Class");

		pcClassNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcClassNameLabel.setText("class");

		jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12));
		jLabel9.setText("Race");

		pcRaceLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcRaceLabel.setText("pcRace");

		jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12));
		jLabel11.setText("Alignment");

		pcAlignmentLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcAlignmentLabel.setText("align");

		jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12));
		jLabel7.setText("Level");

		pcClassLevelLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcClassLevelLabel.setText("pcClassLevel");

		jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12));
		jLabel1.setText("Player");

		pcPlayerNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcPlayerNameLabel.setText("pcName");

		jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 12));
		jLabel13.setText("Move");

		pcMoveBaseLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcMoveBaseLabel.setText("move");

		jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12));
		jLabel6.setText("EXP");
		jLabel6.setToolTipText("Total Experience");

		pcExperienceTotalsLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcExperienceTotalsLabel.setText("pcExperience");

		jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 12));
		jLabel45.setText("HP   ");
		jLabel45.setToolTipText("Maximum hitpoints.");

		pcMaxHPLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcMaxHPLabel.setText("999");

		jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 12));
		jLabel29.setText("AC");
		jLabel29.setToolTipText("Armor Class");

		pcArmorClassLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcArmorClassLabel.setText("-10");
		pcArmorClassLabel.setToolTipText("Normal Armor Class.");

		jLabel31.setText("/");

		pcArmorClassShieldlessLabel
				.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcArmorClassShieldlessLabel.setText("-10");
		pcArmorClassShieldlessLabel
				.setToolTipText("Armor class without shield");

		jLabel33.setText("/");

		pcArmorClassRearLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcArmorClassRearLabel.setText("-10");
		pcArmorClassRearLabel.setToolTipText("Armor class from rear.");

		jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 12));
		jLabel47.setText("THACO");
		jLabel47.setToolTipText("To hit armor class 0 value.");

		pcTHACOLabel.setFont(new java.awt.Font("Segoe UI", 1, 15));
		pcTHACOLabel.setText("00");

		javax.swing.GroupLayout detailsPanelLayout = new javax.swing.GroupLayout(
				detailsPanel);
		detailsPanel.setLayout(detailsPanelLayout);
		detailsPanelLayout
				.setHorizontalGroup(detailsPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								detailsPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												detailsPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel3)
														.addComponent(jLabel5)
														.addComponent(jLabel13)
														.addComponent(jLabel45))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												detailsPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																pcMaxHPLabel)
														.addComponent(
																pcMoveBaseLabel)
														.addComponent(
																pcClassNameLabel)
														.addComponent(
																pcCharacterNameLabel))
										.addGap(20, 20, 20)
										.addGroup(
												detailsPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel1)
														.addComponent(jLabel7)
														.addComponent(jLabel9)
														.addComponent(jLabel29))
										.addGap(8, 8, 8)
										.addGroup(
												detailsPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																pcClassLevelLabel)
														.addComponent(
																pcPlayerNameLabel)
														.addComponent(
																pcRaceLabel)
														.addGroup(
																detailsPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				pcArmorClassLabel)
																		.addGap(0,
																				0,
																				0)
																		.addComponent(
																				jLabel31)
																		.addGap(0,
																				0,
																				0)
																		.addComponent(
																				pcArmorClassShieldlessLabel)
																		.addGap(0,
																				0,
																				0)
																		.addComponent(
																				jLabel33)
																		.addGap(0,
																				0,
																				0)
																		.addComponent(
																				pcArmorClassRearLabel)))
										.addGap(20, 20, 20)
										.addGroup(
												detailsPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel47)
														.addComponent(jLabel11)
														.addComponent(jLabel6))
										.addGap(8, 8, 8)
										.addGroup(
												detailsPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																pcExperienceTotalsLabel)
														.addComponent(
																pcAlignmentLabel)
														.addComponent(
																pcTHACOLabel))
										.addContainerGap(144, Short.MAX_VALUE)));
		detailsPanelLayout
				.setVerticalGroup(detailsPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								detailsPanelLayout
										.createSequentialGroup()
										.addGroup(
												detailsPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel1)
														.addComponent(
																pcPlayerNameLabel)
														.addComponent(
																pcCharacterNameLabel)
														.addComponent(jLabel3))
										.addGap(2, 2, 2)
										.addGroup(
												detailsPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel5)
														.addComponent(
																pcClassNameLabel)
														.addComponent(jLabel7)
														.addGroup(
																detailsPanelLayout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				pcClassLevelLabel)
																		.addComponent(
																				jLabel6)
																		.addComponent(
																				pcExperienceTotalsLabel)))
										.addGap(2, 2, 2)
										.addGroup(
												detailsPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel13)
														.addComponent(
																pcMoveBaseLabel)
														.addComponent(
																pcRaceLabel)
														.addComponent(jLabel9)
														.addComponent(jLabel11)
														.addComponent(
																pcAlignmentLabel))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												detailsPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel45)
														.addComponent(
																pcMaxHPLabel)
														.addComponent(jLabel29)
														.addComponent(
																pcArmorClassLabel)
														.addComponent(jLabel31)
														.addComponent(
																pcArmorClassShieldlessLabel)
														.addComponent(jLabel33)
														.addComponent(
																pcArmorClassRearLabel)
														.addComponent(
																pcTHACOLabel)
														.addComponent(jLabel47))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		add(detailsPanel, java.awt.BorderLayout.CENTER);
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JPanel detailsPanel;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel29;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel31;
	private javax.swing.JLabel jLabel33;
	private javax.swing.JLabel jLabel45;
	private javax.swing.JLabel jLabel47;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JLabel pcAlignmentLabel;
	private javax.swing.JLabel pcArmorClassLabel;
	private javax.swing.JLabel pcArmorClassRearLabel;
	private javax.swing.JLabel pcArmorClassShieldlessLabel;
	private javax.swing.JLabel pcCharacterNameLabel;
	private javax.swing.JLabel pcClassLevelLabel;
	private javax.swing.JLabel pcClassNameLabel;
	private javax.swing.JLabel pcExperienceTotalsLabel;
	private javax.swing.JLabel pcMaxHPLabel;
	private javax.swing.JLabel pcMoveBaseLabel;
	private javax.swing.JLabel pcPlayerNameLabel;
	private javax.swing.JLabel pcRaceLabel;
	private javax.swing.JLabel pcTHACOLabel;
	// End of variables declaration//GEN-END:variables

}