/*
 * Table_Generator_Details.java
 *
 * Created on __DATE__, __TIME__
 */

package org.ost.main;

/**
 *
 * @author  __USER__
 */
public class Table_Generator_Details extends javax.swing.JPanel {

	/** Creates new form Table_Generator_Details */
	public Table_Generator_Details() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		subPanel = new javax.swing.JPanel();
		diceLabel = new javax.swing.JLabel();
		nameLabel = new javax.swing.JLabel();
		referToLabel = new javax.swing.JLabel();

		setBackground(new java.awt.Color(204, 204, 204));
		setLayout(new java.awt.GridLayout());

		subPanel.setBackground(new java.awt.Color(204, 204, 204));
		subPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		diceLabel.setFont(new java.awt.Font("Segoe UI", 0, 10));
		diceLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		diceLabel.setText("00-00");
		subPanel.add(diceLabel);

		nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 10));
		nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		nameLabel.setText("Name");
		subPanel.add(nameLabel);

		add(subPanel);

		referToLabel.setFont(new java.awt.Font("Segoe UI", 0, 10));
		referToLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		referToLabel.setText("ReferTo");
		add(referToLabel);
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	public javax.swing.JLabel diceLabel;
	public javax.swing.JLabel nameLabel;
	public javax.swing.JLabel referToLabel;
	public javax.swing.JPanel subPanel;
	// End of variables declaration//GEN-END:variables

}