/*
 * TreasureTypePanel.java
 *
 * Created on __DATE__, __TIME__
 */

package org.ost.main;

import java.util.Comparator;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author  __USER__
 */
public class TreasureTypePanel extends javax.swing.JPanel {

	/** Creates new form TreasureTypePanel */
	public TreasureTypePanel(char incomingChar) {
		initComponents();
		myType = incomingChar;
		//		myTypeString = String.format("%c",incomingChar);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		typeCheckBox = new javax.swing.JCheckBox();
		typeLabel = new javax.swing.JLabel();
		modelTypeCountSpinner = new SpinnerNumberModel(new Integer(0),
				new Integer(0), new Integer(100), new Integer(1));
		typeSpinner = new javax.swing.JSpinner(modelTypeCountSpinner);

		setBackground(new java.awt.Color(204, 204, 204));
		setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));
		setMinimumSize(new java.awt.Dimension(86, 30));
		setPreferredSize(new java.awt.Dimension(86, 30));
		setLayout(new java.awt.GridLayout());

		typeCheckBox.setBackground(new java.awt.Color(204, 204, 204));
		typeCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 8));
		typeCheckBox.setIconTextGap(0);
		typeCheckBox.setMaximumSize(new java.awt.Dimension(20, 20));
		typeCheckBox.setMinimumSize(new java.awt.Dimension(20, 20));
		typeCheckBox.setPreferredSize(new java.awt.Dimension(20, 20));
		add(typeCheckBox);

		typeLabel.setFont(new java.awt.Font("Segoe UI", 1, 10));
		typeLabel.setText("A");
		add(typeLabel);

		typeSpinner.setModel(modelTypeCountSpinner);
		typeSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(
				typeSpinner, ""));
		typeSpinner.setMinimumSize(new java.awt.Dimension(40, 22));
		typeSpinner.setPreferredSize(new java.awt.Dimension(40, 22));
		typeSpinner.setValue(new Integer(1));
		add(typeSpinner);
	}// </editor-fold>
	//GEN-END:initComponents

	//	/**
	//	 * sort TreasureTypePanel by name
	//	 * 
	//	 */
	//	private class typeSortByName implements Comparator<TreasureTypePanel> {
	//		public int compare(TreasureTypePanel o1, TreasureTypePanel o2) {
	//			return o1.myTypeString.toUpperCase().compareTo((o2).myTypeString.toUpperCase());
	//		}
	//
	//	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	public javax.swing.JCheckBox typeCheckBox;
	public javax.swing.JLabel typeLabel;
	public javax.swing.JSpinner typeSpinner;
	// End of variables declaration//GEN-END:variables
	public SpinnerNumberModel modelTypeCountSpinner;
	public char myType;
	//public String myTypeString;
}